# Generated by Django 5.0.1 on 2024-01-11 18:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegularFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('idealfor', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.allproducts')),
            ],
        ),
        migrations.CreateModel(
            name='RelaxedFit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric', models.CharField(blank=True, max_length=255, null=True)),
                ('idealfor', models.CharField(blank=True, max_length=255, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app.allproducts')),
            ],
        ),
    ]
